services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coursesphere-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./database.db
    restart: always

