services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000 # Aqui você mudará no deploy
    ports:
      - "5173:80"
    networks:
      - coursesphere-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - ./backend:/app
    networks:
      - coursesphere-network

networks:
  coursesphere-network:
    driver: bridge